 name: gitartwork for Thanks Note
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       
         with:
            # Use this username's contribution graph  
            user_name: Va-Rohith
            # Text on contribution graph 
            text: THANK U
       
       
